name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  deployments: write

env:
  NODE_VERSION: '20.x'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          [cite_start]cache: 'npm' 

      - run: npm install
      - run: npm test

      - name: Upload Test Report
        [cite_start]if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: coverage/ 

  build:
    [cite_start]needs: test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build --if-present
      
      - name: Save Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          [cite_start]path: dist/ 

  deploy:
    needs: build
    [cite_start]if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    [cite_start]environment: production 
    steps:
      - name: Simulation of Deploy
        run: |
          echo "Deploying to server using secret token..."
          echo "Token: ${{ secrets.DEPLOY_TOKEN }}" # Робота з секретами [cite: 53]
